//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStudy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_User
    {
        public string Id { get; set; }
        public string Account { get; set; }
        public string RealName { get; set; }
        public string NickName { get; set; }
        public string HeadIcon { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string MobilePhone { get; set; }
        public string Email { get; set; }
        public string WeChat { get; set; }
        public string ManagerId { get; set; }
        public Nullable<int> SecurityLevel { get; set; }
        public string Signature { get; set; }
        public string OrganizeId { get; set; }
        public string DepartmentId { get; set; }
        public string RoleId { get; set; }
        public string DutyId { get; set; }
        public Nullable<bool> IsAdministrator { get; set; }
        public Nullable<int> SortCode { get; set; }
        public Nullable<bool> DeleteMark { get; set; }
        public Nullable<bool> EnabledMark { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatorTime { get; set; }
        public string CreatorUserId { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
        public string LastModifyUserId { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public string DeleteUserId { get; set; }
    }
}
